name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'CodeNinjah thanks you for your first issue'
        pr-message: 'CodeNinjah thanks you for your PR and will get back to you in 2-5 days'
